const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('help')
    .setDescription('Show available bot commands and how to use them.'),

  async execute(interaction) {
    await interaction.reply({
      content: [
        '📖 **Kabayo Officer Bot — Commands**',
        '',
        '👤 **Member Commands:**',
        '`/status [@user]` — View status',
        '`/leaderboard` — Weekly leaderboard',
        '`/dm-warnings enabled:<bool>` — Toggle DM reminders',
        '`/week status` — View current week overview & countdown',
        '`/link-profile uma-name:<name>` — Link your uma.moe trainer name',
        '`/feedback type:<type> message:<text>` — Send feedback to officers',
        '`/ask question:<text>` — Ask the offline AI assistant (requires local Ollama)',
        '`/stats [@user]` — View guild or member statistics',
        '`/me` — Your personal comprehensive summary',
        '`/top` — Top 5 members by fans this week',
        '`/daily-diff` — Today vs yesterday fan difference for all members',
        '`/goal` — See how many fans you need for the next tier',
        '`/compare user:@member` — Compare your stats with another member',
        '`/hall-of-fame` — All-time guild records',
        '`/help` — This message',
        '',
        '🛡️ **Officer Commands** (Guild Officer + Leader):',
        '`/submit fans:<n> user:@member` — Add fans to a member\'s total',
        '`/set-fans user:@member fans:<n>` — Set exact fan count',
        '`/adjust user:@member fans:<number> reason:<text>` — Adjust fans',
        '`/week start` — Announce new week',
        '`/week close` — Close the week',
        '`/week reset` — Reset all weekly data',
        '`/week init [week:<label>]` — Initialize week (first-time setup)',
        '`/set-channels` — Configure bot channels',
        '`/set-roles` — Configure reward roles',
        '`/set-thresholds min:<n> target:<n> elite:<n>` — Change fan thresholds',
        '`/auto-import` — Import fans from uma.moe',
        '`/debug-import` — Debug import info without updating DB',
        '`/import-status` — Check last import results',
        '`/set-circle id:<id>` — Set uma.moe circle ID',
        '`/set-bot-channels [commands:#channel]` — Restrict bot commands to a channel',
        '`/test-notification type:<type>` — Trigger a scheduled notification immediately',
        '`/link-profile uma-name:<name> user:@member` — Link another member\'s trainer name',
        '`/vacation set user:@member weeks:<n> [reason:<text>]` — Mark member as on vacation',
        '`/vacation remove user:@member` — End a member\'s vacation',
        '`/note user:@member [text:<note>]` — Add or view private notes',
        '`/backup` — Download the database file',
        '`/export` — Export member data as CSV',
        '`/reset-leaderboard confirm:CONFIRM [clear-history]` — Wipe all fan data for clean re-import',
        '',
        '👑 **Leader Commands** (Guild Leader only):',
        '`/set-officer-roles` — Define officer/leader/member roles',
        '',
        '⏰ **Automatic Schedule (JST):**',
        'Daily 01:00, 07:00, 13:00, 19:00 — Auto-import from uma.moe',
        'Mon 04:05 — New week announcement',
        'Thu 12:00 — Midweek checkpoint',
        'Sun 10:00 — Push Day morning',
        'Sun 18:00 — Push Day evening',
        'Mon 02:00 — Final push DMs',
        'Mon 03:55 — Week close + report + auto-backup',
      ].join('\n'),
      ephemeral: true,
    });
  },
};

