const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('help')
    .setDescription('Show available bot commands and how to use them.'),

  async execute(interaction) {
    await interaction.reply({
      content: [
        '## 📖 Kabayo Officer Bot — Help',
        '',
        '**Member Commands:**',
        '',
        '**`/register ign:<name> [dm_warnings:true|false]`**',
        '→ Link your Discord account to your in-game name. Optionally enable/disable DM warnings.',
        '',
        '**`/submit fans:<number> [user:@member]`**',
        '→ Submit your weekly fan count. Officers can submit on behalf of another member.',
        '',
        '**`/status [user:@member]`**',
        '→ Check the current weekly status of yourself or another member.',
        '',
        '**`/leaderboard [type:week|season] [sort:top|bottom] [count:n]`**',
        '→ Display the guild fan leaderboard.',
        '',
        '**`/dm-warnings enabled:<true|false>`**',
        '→ Toggle whether you receive DM reminders and warnings.',
        '',
        '**`/help`**',
        '→ Show this help message.',
        '',
        '**Officer Commands (requires Manage Server):**',
        '',
        '**`/set-channels tracker:<#> results:<#> push:<#> officer:<#> hof:<#>`**',
        '→ Configure which channels the bot posts in.',
        '',
        '**`/set-roles mvp:<@role> elite:<@role> core:<@role> risk:<@role>`**',
        '→ Configure automatic performance roles.',
        '',
        '**`/adjust user:<@member> fans:<number> reason:<text>`**',
        "→ Correct a member's weekly fan count.",
        '',
        '**`/week start`**',
        '→ Announce the start of a new week.',
        '',
        '**`/week close`**',
        '→ Manually close the week and generate the report.',
        '',
        '**`/week reset`**',
        '→ Reset all weekly fans to 0 (emergency/testing).',
        '',
        '**Status Tiers:**',
        '🟢 **GREEN** — Strong Performance (≥ 4.8M fans)',
        '🟡 **YELLOW** — On Track (≥ 4.2M fans)',
        '🔴 **RED** — Needs Attention (< 4.2M fans)',
        '⚡ **ELITE** — Outstanding (≥ 5.5M fans)',
        '',
        '**Automated Schedule (Europe/Madrid):**',
        '• Monday 00:00 — New week announcement',
        '• Thursday 20:00 — Midweek checkpoint + DM reminders',
        '• Sunday 10:00 — Push Day morning reminder',
        '• Sunday 18:00 — Push Day evening update',
        '• Sunday 22:00 — Final push DM to members below target',
        '• Sunday 23:00 — Automatic week close + report',
      ].join('\n'),
      ephemeral: true,
    });
  },
};
